rispo_yandex_kassa_check_order:
    path:  /yandex_kassa/check_order
    defaults: { _controller: RispoYandexKassaBundle:Default:checkOrder, _format: xml }

rispo_yandex_kassa_payment_aviso:
    path:  /yandex_kassa/payment_aviso
    defaults: { _controller: RispoYandexKassaBundle:Default:paymentAviso, _format: xml }

rispo_yandex_kassa_success:
    path:  /yandex_kassa/success
    defaults: { _controller: RispoYandexKassaBundle:Default:success }

rispo_yandex_kassa_fail:
    path:  /yandex_kassa/fail
    defaults: { _controller: RispoYandexKassaBundle:Default:fail }